### PR TITLE
Remove IAM and Timesync

### PR DESCRIPTION
**Pull request by sharoninator**
Removed timesync and iam from the app2 and app3 recipes.

### CODE REVIEW

**Comment by ramereth** [comment]
@sharoninator before we can merge this, I forgot that we need to remove the references to timesync and iam from osl-haproxy. Can you make a PR which does that first please?

**Comment by ramereth** [comment]
LGTM but we need to hold on merging/deploying this

**Comment by sharoninator** [comment]
Hey,
Here's the PR for haproxy.
https://github.com/osuosl-cookbooks/osl-haproxy/pull/294

**Comment by sharoninator** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.5.0.  Have a nice day!

**Pull request merged**
