### PR TITLE
Upgrade NodeJS to LTS v6.9.1.

### PR DESCRIPTION
**Pull request by LyonesGamer**

### CODE REVIEW

**Comment by LyonesGamer** [comment]
@ramereth We were looking at doing this in preparation to move timesync-node over to an Ansible/systemd deployment system instead of being Chef-managed. The upgrade is needed because v6 is the current LTS; v4 will be dropped from LTS in April. We just wanted to do the transition now, while we're setting things up, rather than have to go through a transition process later.

**Comment by ramereth** [comment]
Fails converge with:

``Checksum on resource (a9d9e6) does not match checksum on content (d4eb16)``

**Comment by LyonesGamer** [comment]
@ramereth Looks like the issue was that there's both a .tar.gz and a .tar.xz for node, and Chef had been using the .tar.gz for v4, so I used that checksum, but now it's using the .tar.xz for v6, so I used the wrong checksum. Should be fixed now; kitchen converges fine.

**Comment by LyonesGamer** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.8.0.  Have a nice day!

**Pull request merged**
