### PR TITLE
Moved app1 staging site to ruby 3.1.4

### PR DESCRIPTION
**Pull request by sectopodwreck**
Slight modification changing the ruby versions for:
* **openid-staging-unicorn** from `2.7.5` to `3.1.4`
*  **openid-staging-delayed-job** from `2.5.3` to `3.1.4`

### CODE REVIEW

**Comment by ramereth** [comment]
@sectopodwreck would you mind squashing your commits into one? That will make reading history better down the road.

**Review by ramereth — APPROVED** [review]
Patch bump

@sectopodwreck please let them know that we went ahead and made this change but will still look into the docker solution in the longer term.

**Comment by sectopodwreck** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v4.3.2.  Have a nice day!

**Pull request merged**
