### PR TITLE
Kennric/streamwebs app3

### PR DESCRIPTION
**Pull request by Kennric**
@ramereth 
Setting up app3 for streamwebs

### CODE REVIEW

**Comment by fahlmant** [comment]
Make sure to rebase/squash

**Comment by Kennric** [comment]
@fahlmant  Squashed.

**Comment by Kennric** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v1.7.0.  Have a nice day!

**Pull request merged**
