### PR TITLE
Chef 13 compatibility fixes

### PR DESCRIPTION
**Pull request by jcorme**

### CODE REVIEW

**Comment by jcorme** [comment]
[Chef 13: osl-app](https://trello.com/c/mDGnAE1r/925-chef-13-osl-app)

**Comment by ramereth** [comment]
@jcorme I've been wanting to create a custom resource for this cookbook for a long time which covers the basics of what we do for each app. Basically, setup the user, sudo and systemd service. Think you could do that in this PR too?

**Comment by ramereth** [comment]
@jcorme please get an additional review before merging

**Comment by jcorme** [comment]
!bump major *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v2.0.0.  Have a nice day!

**Pull request merged**
