### PR TITLE
Redmine replicant on app2

### PR DESCRIPTION
**Pull request by fahlmant**
Attempting to move replicant's redmine to app2 so we can get closer to being done with hackberry. Not sure what more needs to be done here

### CODE REVIEW

**Comment by fahlmant** [comment]
[Legacy Apps (ruby): redmine.replicant.us (redmine)](https://trello.com/c/ZZ2ZZPdV/248-legacy-apps-ruby-redmine-replicant-us-redmine)

**Comment by ramereth** [comment]
@fahlmant do you need more input on this before moving forward?

**Comment by fahlmant** [comment]
@ramereth yes

**Comment by ramereth** [comment]
@fahlmant looks like the newer rubocop is failing on libraries/helpers.rb. Mind fixing that up?

**Comment by fahlmant** [comment]
The library definition for `sudo_commands` is causing rubocop to complain. Changing to make rubocop happy makes all of the places this is used (14 places between 3 cookbooks) fail. IMO, this should done in a different PR.

**Comment by ramereth** [comment]
@fahlmant huh? If I make this change:

``` diff
 def sudo_commands(*args)
-  args.reduce([]) { |a, e| a + systemctl_commands(e) }
+  args.reduce([]) { |acc, elem| acc + systemctl_commands(elem) }
 end
```

The spec tests still work. Does it do something different for you?

**Comment by fahlmant** [comment]
@ramereth I used rubocop --auto-correct, which did something else. Your suggestion fixes it. Changing

**Comment by fahlmant** [comment]
@osuosl-cookbooks/chefs Ready for review.

**Comment by fahlmant** [comment]
!bump patch ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.10.5.  Have a nice day!

**Pull request merged**
