### PR TITLE
Chef 16 Fixes

### PR DESCRIPTION
**Pull request by zimmerry**

### CODE REVIEW

**Comment by zimmerry** [comment]
[Chef 16: osl-app](https://trello.com/c/7PLNzhoE/1993-chef-16-osl-app)

**Review by ramereth — APPROVED** [review]
Please do a minor bump.

**Comment by zimmerry** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.7.0.  Have a nice day!

**Pull request merged**
