### PR TITLE
rename the redmine app systemd service aptly

### PR DESCRIPTION
**Pull request by knightsamar**
I will kill and rm the old service manually ~once the new one starts~ just after the PR is approved and before a chef-client run, if that's okay with the on call.

### CODE REVIEW

**Comment by ramereth** [comment]
If we're going to move towards unicorn anyways, we should just keep the name IMO.

**Comment by knightsamar** [comment]
@ramereth it doesn't reflect the current state and we aren't moving there any soon. that's my only reason for this PR
.

**Comment by ramereth** [comment]
The original intention was to use unicorn, however we ran into problems with the old version we were on. I can't remember, are we using the same old version or a newer version that better supports unicorn?

**Comment by knightsamar** [comment]
@ramereth we upgraded to v3.3.3

**Comment by knightsamar** [comment]
Ok will take it up. Closing this PR in favor of that.

**Pull request closed without merging**
