### PR TITLE
updated ruby for openid-staging-unicorn

### PR DESCRIPTION
**Pull request by FrankreedX**

### CODE REVIEW

**Review by ramereth — APPROVED** [review]
Please do a patch bump

**Comment by FrankreedX** [comment]
!bump minor~

**Comment by ramereth** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v4.2.0.  Have a nice day!

**Comment by ramereth** [comment]
@FrankreedX You didn't have a space between `minor` and `~` which is why this didn't get triggered.

**Pull request merged**
