### PR TITLE
Replicant Redmine fix & DB cleanup

### PR DESCRIPTION
**Pull request by detjensrobert**
- updates Replicant Redmine version to fix activity Atom feed
- updates the testing databases to be more sane
- adds tests for checking that Docker env variables are set correctly.

### CODE REVIEW

**Comment by detjensrobert** [comment]
[#31426: Broken Redmine forums atom feed](https://trello.com/c/4k7tZj7w/2161-31426-broken-redmine-forums-atom-feed)

**Review by ramereth — APPROVED** [review]
Minor bump please.

**Comment by detjensrobert** [comment]
!bump minor ~

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a minor-level version bump to v2.9.0.  Have a nice day!

**Pull request merged**
