### PR TITLE
Adds right amount of spacing between guincorn params.

### PR DESCRIPTION
**Pull request by knightsamar**
We need space between the end and beginning of different options for gunicorn.

### CODE REVIEW

**Comment by knightsamar** [comment]
This is a fix to #29

**Comment by knightsamar** [comment]
Fixed.

**Comment by knightsamar** [comment]
!bump patch *

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.10.7.  Have a nice day!

**Pull request merged**
